make:
	javac -d build src/zeionara/couples/FreeMan.java src/zeionara/couples/Main.java src/zeionara/couples/Prefs.java src/zeionara/couples/OrderedPrefs.java src/zeionara/couples/IntArray.java src/zeionara/couples/DataStore.java src/zeionara/couples/IntMatrix.java
run:
	java -cp build/ zeionara.couples.Main 5 
mr:
	javac -d build src/zeionara/couples/FreeMan.java src/zeionara/couples/Main.java src/zeionara/couples/Prefs.java src/zeionara/couples/OrderedPrefs.java src/zeionara/couples/IntArray.java src/zeionara/couples/DataStore.java src/zeionara/couples/IntMatrix.java
	java -cp build/ zeionara.couples.Main 5 
